name: suratizin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  pdf: ^3.7.3
  path_provider: ^2.0.9
  open_file: ^3.2.1
  flutter_native_splash: ^2.1.3+1
  syncfusion_flutter_pdf: ^20.1.47-beta.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/image/1.png
  android_12: null

